services:
    api:
        image: only1adwy/todo-api:latest
        volumes:
            - sqlite-volume:/TodoAPI/Database
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        deploy:
            mode: replicated
            replicas: 2
            update_config:
                parallelism: 1
            restart_policy:
                condition: on-failure
        labels:
            - "com.centurylinklabs.watchtower.enable=true"

    nginx:
        image: nginx:alpine
        container_name: nginx_reverse_proxy
        ports:
            - "8070:8070"
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - /var/run/docker.sock:/tmp/docker.sock:ro
        depends_on:
            - api
        labels:
            - "com.centurylinklabs.watchtower.enable=true"

volumes:
    sqlite-volume:

networks:
    default:
        driver: bridge
        name: todo-network
