services:
    cache:
        image: redis:alpine
        container_name: todo-redis-cache
        ports:
            - "6379:6379"
        networks:
            - todo-network
        labels:
            - "com.centurylinklabs.watchtower.enable=true"

    api:
        image: only1adwy/todo-api:latest
        volumes:
            - sqlite-volume:/Todo/Database
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:8080;https://+:8443
        deploy:
            mode: replicated
            replicas: 2
            update_config:
                parallelism: 1
            restart_policy:
                condition: on-failure
        depends_on:
            - cache
        networks:
            - todo-network
        command:
            - "sh -c dotnet Todo.Api.dll ef database update && dotnet Todo.Api.dll"
        labels:
            - "com.centurylinklabs.watchtower.enable=true"

    client:
        image: only1adwy/todo-client:latest
        container_name: todo-client
        command: ["npm", "run", "build"]
        environment:
            - VITE_SERVER_URL=https://api.todo.aladawy.duckdns.org/api
            - VITE_SERVER_LOGIN_PATH=Auth/login
            - VITE_SERVER_REGISTER_PATH=Auth/register
            - VITE_SERVER_REFRESH_PATH=Auth/refresh
            - VITE_SERVER_LOGOUT_PATH=Auth/logout
        depends_on:
            - api
        networks:
            - todo-network
        volumes:
            - dist:/Todo
        labels:
            - "com.centurylinklabs.watchtower.enable=true"

    nginx:
        image: nginx:alpine
        container_name: todo-reverse-proxy
        ports:
            - "8070:8070"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - dist:/usr/share/nginx/html
        depends_on:
            - cache
            - api
        networks:
            - todo-network
        labels:
            - "com.centurylinklabs.watchtower.enable=true"

volumes:
    sqlite-volume:
        name: todo-sqlite-volume
    dist:
        name: dist

networks:
    todo-network:
        driver: bridge
        name: todo-network
